# =====================================================
# SkyPeak Hotel - Configuration of the Production environment
# =====================================================

# Port HTTP server (default 8080)
server.port=8080

# Application identification
spring.application.name=skypeak-hotel

# Database PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Liquibase migrations DB
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Default administrator
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# JWT token
jwt.secret=${JWT_TOKEN}
jwt.expiration-ms=3600000
