# =====================================================
# SkyPeak Hotel - Configuration of the Production environment
# =====================================================

# Port HTTP server (default 8080)
server.port=8080

# Application identification
spring.application.name=skypeak-hotel

# Database PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Liquibase migrations DB
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Default administrator
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.first.name=${ADMIN_FIRST_NAME}
admin.last.name=${ADMIN_LAST_NAME}
admin.phone.number=${ADMIN_PHONE_NUMBER}

# JWT token
jwt.secret=${JWT_TOKEN}
jwt.expiration-ms=3600000

# Swagger
# Path to Swagger UI
springdoc.swagger-ui.path=/swagger

# Path to OpenAPI JSON
springdoc.api-docs.path=/v3/api-docs

# Sorting endpoints
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Show request completion time
springdoc.swagger-ui.displayRequestDuration=true

# Enable Swagger UI and OpenAPI JSON
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Expand default sections
springdoc.swagger-ui.docExpansion=none

# Show examples of models
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.defaultModelExpandDepth=1

# Adds Authorize button
springdoc.swagger-ui.persistAuthorization=true

# Telegram bot configuration
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}

# Geo IP
geoip.database.path=${GEOIP_DATABASE_PATH}